### ISSUE TITLE
[Storybook] stack.map is not a function

### ISSUE THREAD

**Issue by thevladbog** [gravity-ui/uikit#1170]
Привет!
На странице компонента https://preview.gravity-ui.com/uikit/?path=/story/components-feedback-progress--default возникает ошибка с собержанием:
stack.map is not a function
```
TypeError: stack.map is not a function
    at Progress_Progress_Progress.renderStack (https://preview.gravity-ui.com/uikit/components-Progress-__stories__-Progress-stories.fc143352.iframe.bundle.js:1:4537)
    at Progress_Progress_Progress.renderContent (https://preview.gravity-ui.com/uikit/components-Progress-__stories__-Progress-stories.fc143352.iframe.bundle.js:1:3714)
    at Progress_Progress_Progress.render (https://preview.gravity-ui.com/uikit/components-Progress-__stories__-Progress-stories.fc143352.iframe.bundle.js:1:3007)
    at kj (https://preview.gravity-ui.com/uikit/8505.88aef0be.iframe.bundle.js:528:545450)
    at ij (https://preview.gravity-ui.com/uikit/8505.88aef0be.iframe.bundle.js:528:545248)
    at Wk (https://preview.gravity-ui.com/uikit/8505.88aef0be.iframe.bundle.js:528:588321)
    at Vk (https://preview.gravity-ui.com/uikit/8505.88aef0be.iframe.bundle.js:528:576564)
    at Uk (https://preview.gravity-ui.com/uikit/8505.88aef0be.iframe.bundle.js:528:576495)
    at Jk (https://preview.gravity-ui.com/uikit/8505.88aef0be.iframe.bundle.js:528:576364)
    at Ok (https://preview.gravity-ui.com/uikit/8505.88aef0be.iframe.bundle.js:528:573220)
```

![image](https://github.com/gravity-ui/uikit/assets/47273232/a0ccc907-02c7-4a2b-9b5e-6277977fa02a)

**Comment by amje** [comment]
@thevladbog What is your OS and browser?

**Comment by thevladbog** [comment]
> @thevladbog What is your OS and browser?

@amje Ya.Browser 23.9.5.660 (64-bit), Windows 11 23H2
The problem is floating. I've found it several times over the last couple of days.

**Comment by thevladbog** [comment]
https://preview.gravity-ui.com/dynamic-forms/?path=/story/array-table--table
Found another error if add more than 10 items in Array in spec

Cannot read properties of undefined (reading 'toLocaleLowerCase')
```
TypeError: Cannot read properties of undefined (reading 'toLocaleLowerCase')
    at https://preview.gravity-ui.com/dynamic-forms/782.2def0ba5.iframe.bundle.js:2:280991
    at https://preview.gravity-ui.com/dynamic-forms/782.2def0ba5.iframe.bundle.js:2:281100
    at Array.filter (<anonymous>)
    at getFilteredFlattenOptions (https://preview.gravity-ui.com/dynamic-forms/782.2def0ba5.iframe.bundle.js:2:280847)
    at Select (https://preview.gravity-ui.com/dynamic-forms/782.2def0ba5.iframe.bundle.js:2:290068)
    at Xh (https://preview.gravity-ui.com/dynamic-forms/621.60823ae4.iframe.bundle.js:401:934340)
    at Zi (https://preview.gravity-ui.com/dynamic-forms/621.60823ae4.iframe.bundle.js:401:944321)
    at Wk (https://preview.gravity-ui.com/dynamic-forms/621.60823ae4.iframe.bundle.js:401:992883)
    at Vk (https://preview.gravity-ui.com/dynamic-forms/621.60823ae4.iframe.bundle.js:401:980029)
    at Uk (https://preview.gravity-ui.com/dynamic-forms/621.60823ae4.iframe.bundle.js:401:979960)
```
![image](https://github.com/gravity-ui/uikit/assets/47273232/98bee4a6-027f-465e-b064-a3506040ea96)

**Comment by amje** [comment]
> https://preview.gravity-ui.com/dynamic-forms/?path=/story/array-table--table Found another error if add more than 10 items in Array in spec
> 
> Cannot read properties of undefined (reading 'toLocaleLowerCase')
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'toLocaleLowerCase')
>     at https://preview.gravity-ui.com/dynamic-forms/782.2def0ba5.iframe.bundle.js:2:280991
>     at https://preview.gravity-ui.com/dynamic-forms/782.2def0ba5.iframe.bundle.js:2:281100
>     at Array.filter (<anonymous>)
>     at getFilteredFlattenOptions (https://preview.gravity-ui.com/dynamic-forms/782.2def0ba5.iframe.bundle.js:2:280847)
>     at Select (https://preview.gravity-ui.com/dynamic-forms/782.2def0ba5.iframe.bundle.js:2:290068)
>     at Xh (https://preview.gravity-ui.com/dynamic-forms/621.60823ae4.iframe.bundle.js:401:934340)
>     at Zi (https://preview.gravity-ui.com/dynamic-forms/621.60823ae4.iframe.bundle.js:401:944321)
>     at Wk (https://preview.gravity-ui.com/dynamic-forms/621.60823ae4.iframe.bundle.js:401:992883)
>     at Vk (https://preview.gravity-ui.com/dynamic-forms/621.60823ae4.iframe.bundle.js:401:980029)
>     at Uk (https://preview.gravity-ui.com/dynamic-forms/621.60823ae4.iframe.bundle.js:401:979960)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/47273232/286690401-98bee4a6-027f-465e-b064-a3506040ea96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzk4NzgsIm5iZiI6MTcwMTMzOTU3OCwicGF0aCI6Ii80NzI3MzIzMi8yODY2OTA0MDEtOThiZWU0YTYtMDI3Zi00NjVlLWIwNjQtYTM1MDYwNDBlYTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDEwMTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljY2ExYTAzZTI1YjNmNDcyNGU5ZTAwMWZhYWU1Y2Y1NjQ5ZmZmNjlkOWFlYzlmZDQ3NmU1Zjc1NTY5ZTY2N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o2iW3RZrx7x-s04yCvL9MLtvTTfXT9hnnb_uTul6WqU)

@thevladbog Better to open an issue to the dynamic-forms repo
