### ISSUE TITLE
withTableSettings does not work correctly

### ISSUE THREAD

**Issue by DenVilk** [gravity-ui/uikit#1279]
I'm using example from [here](https://gravity-ui.com/components/uikit/table#example-3) and getting error due disabling fields in table.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at Table.js:201:163
    at Array.map (<anonymous>)
    at _Table.renderColgroup (Table.js:201:69)
    at _Table.renderTable (Table.js:225:18)
    at _Table.render (Table.js:193:56)
    at finishClassComponent (react-dom.development.js:19752:31)
    at updateClassComponent (react-dom.development.js:19698:24)
    at beginWork (react-dom.development.js:21611:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
 ```
 
 What I do wrong?

**Comment by DenVilk** [comment]
Sorry, it's my fault  ;-(
